format = """
$directory\
$conda\
$git_branch\
$package\
$cmd_duration\
$character\
"""

[directory]
read_only = " ï ½"

[directory.substitutions]
#"Documents" =  "Documents ïœ˜ "
#"Downloads" = "Downloads ï€™ "
#"Music" = "Music ï€ "
##"Pictures" = "Pictures ï€¾ "


[character]


[cmd_duration]
min_time = 500
show_milliseconds = false
disabled = true
format = " ğŸ•™ $duration($style) "
style = "bold italic #87A752"


[sudo]
style = "bold green"
symbol = "ğŸ‘©â€ğŸ’» "
disabled = false

[git_branch]

[conda]
format = "[$environment](dimmed green) "







[java]
symbol = "î‰– "

[julia]
symbol = "î˜¤ "

[memory_usage]
symbol = "ï¡š "

[package]
symbol = "ï£– "

[python]
symbol = "îˆµ "

